# Python Numpy

In [ ]:
import numpy as np

#creating array

In [ ]:
arr0d = np.array(24)    #0-D
arr0d

array(24)

In [ ]:
arr1d = np.array([1,2,3,4,5])  #1-D
arr1d

array([1, 2, 3, 4, 5])

In [ ]:
arr2d = np.array(([1,2],[3,4]))  #2-D
arr2d

array([[1, 2],
       [3, 4]])

In [ ]:
arr3d = np.array([[[2,5],[6,8]],[[10,11],[34,99]]])
arr3d

array([[[ 2,  5],
        [ 6,  8]],

       [[10, 11],
        [34, 99]]])

# Dimension
is the deapth of an array

#Numpy Attributes

In [ ]:
# shape
arr0d.shape, arr1d.shape, arr2d.shape, arr3d.shape

((), (5,), (2, 2), (2, 2, 2))

In [ ]:
# size
print(arr1d.size)
print(arr3d.size)

5
8


In [ ]:
# dtpye

print(arr1d.dtype)
print(arr3d.dtype)

int64
int64


In [ ]:
# ndim
print(arr3d.ndim)

3


# Numpy stores same type of data i.e.,it is homogeneous in nature

In [ ]:
arr = np.array([10,45.6,80,98,100,"Apple"])
arr

array(['10', '45.6', '80', '98', '100', 'Apple'], dtype='<U32')

In [ ]:
arr = np.array([10,45.6,80,98,100,0], dtype=bool)
arr

array([ True,  True,  True,  True,  True, False])

In [ ]:
arr = np.array([10,45.6,80,98,100,0], dtype=str)
arr

array(['10', '45.6', '80', '98', '100', '0'], dtype='<U4')

In [ ]:
np.array([10,45,41,29,87], dtype='int8')

array([10, 45, 41, 29, 87], dtype=int8)

In [ ]:
np.array([10,45,41,29,127,-128],dtype='int8')  # signed integers

array([  10,   45,   41,   29,  127, -128], dtype=int8)

In [ ]:
np.array([10,45,41,29,127,255], dtype='uint8')     # unsigned integers

array([ 10,  45,  41,  29, 127, 255], dtype=uint8)

# Indexing and Slicing

In [ ]:
arr = np.array([1,2,3,4,5])   # start:end:stop
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr[0], arr[-1]

(np.int64(1), np.int64(5))

In [ ]:
arr[1:4]

array([2, 3, 4])

In [ ]:
#### 2-D array

arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[10,0,1,100,8],[1,1,7,3,9]])
arr


array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 10,   0,   1, 100,   8],
       [  1,   1,   7,   3,   9]])

In [ ]:
arr[2][3]

np.int64(100)

In [ ]:
arr[2,3]

np.int64(100)

In [ ]:
arr[0::2,0:]

array([[  1,   2,   3,   4,   5],
       [ 10,   0,   1, 100,   8]])

In [ ]:
arr[0::2,0::2]

array([[ 1,  3,  5],
       [10,  1,  8]])

In [ ]:
arr

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 10,   0,   1, 100,   8],
       [  1,   1,   7,   3,   9]])

In [ ]:
# get the corner values in all size of array

arr[[0,0,-1,-1],[0,-1,0,-1]]

array([1, 5, 1, 9])

In [ ]:
arr[[0,-1],[[0],[-1]]]

array([[1, 1],
       [5, 9]])

In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[10,0,1,100,8]])
arr[[0,-1],[[0],[-1]]]

array([[ 1, 10],
       [ 5,  8]])

# Special arrays

# Zeros

In [ ]:
np.zeros((3))

array([0., 0., 0.])

In [ ]:
np.zeros((3,3), dtype='i')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

# Ones

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# eye: identity array

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

# full()

In [ ]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

# Array operation

In [ ]:
arr = np.array([[1,2,3,4,5],[5,6,7,8,9]])
arr

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [ ]:
arr+2

array([[ 3,  4,  5,  6,  7],
       [ 7,  8,  9, 10, 11]])

In [ ]:
arr**2

array([[ 1,  4,  9, 16, 25],
       [25, 36, 49, 64, 81]])

In [ ]:
arr%3

array([[1, 2, 0, 1, 2],
       [2, 0, 1, 2, 0]])

# Random Array Generation

In [ ]:
import numpy as np

#rand()

In [ ]:
# randomly generated number between 0 to 1
np.random.rand()

0.9937033356283637

In [ ]:
np.random.rand(3)

array([0.11241893, 0.92287401, 0.25075291])

In [ ]:
np.random.rand(3,2)

array([[0.82046089, 0.47054637],
       [0.45873211, 0.15699998],
       [0.57404832, 0.78478387]])

#randn()

In [ ]:
# normal data distribution
normal_data= np.random.randn(10)
normal_data

array([-1.5566738 , -0.77855703, -0.19962352,  0.18922977,  1.99330556,
       -2.16235613,  0.89273461,  2.37891671,  0.7981779 , -0.91656508])

#randint()

In [ ]:
np.random.randint(10,20)

18

In [ ]:
np.random.randint(10,20,(3,3))

array([[13, 18, 10],
       [16, 12, 13],
       [15, 10, 10]])

In [ ]:
np.random.randint(10,20,(3,3,2))

array([[[11, 15],
        [16, 16],
        [14, 12]],

       [[11, 15],
        [10, 12],
        [16, 10]],

       [[19, 12],
        [15, 13],
        [15, 14]]])

# How to repreduce the same array again

#seed()

In [ ]:
np.random.seed(41)
np.random.randint(10,20,(3,3))

array([[10, 13, 12],
       [10, 11, 13],
       [19, 17, 15]])

In [ ]:
np.random.seed(7366425)
np.random.randint(10,20,(3,3))

array([[10, 19, 17],
       [11, 14, 12],
       [14, 18, 16]])

#shuffle()

In [ ]:
arr=np.array([1,2,3,4,5])
np.random.shuffle(arr)
print(arr)

[2 3 1 4 5]


#choice()

# Random Sampling with Replacement

In [ ]:
np.random.choice([10,20,89,100,101,0,1,6])

np.int64(0)

In [ ]:
np.random.choice([10,20,89,100,101,0,1,6],
p=[0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.3],size=(8,8),replace=True)

array([[ 89,   6, 101,   6,   0,  10,   6,   6],
       [  1,  10,  89,  10, 101, 101,  89, 100],
       [  6,   1,  10,   6,  89, 101,   6,   6],
       [ 10, 100,   1,   6,   1,  10,  20,   0],
       [  6,   6,  89,   6, 101,  10, 100,  10],
       [  0,  20,   6,   6,   1,   6,  89,   1],
       [  6,  20,   1,   1, 101,   6,   1,   6],
       [ 89,   6,  10,   6,   6,   0,   0,  10]])

# Example of Rolling Dice

In [ ]:
# 1 to 6
np.random.choice([1,2,3,4,5,6],size=1)

array([1])

#choice with boolean values

In [ ]:
np.random.choice([True,False],size=(2,2))

array([[False,  True],
       [ True, False]])

# Data Alalysis Functions

In [ ]:
np.random.seed(10)
arr=np.random.randint(10,30,(4,4))
arr

array([[19, 14, 25, 10],
       [27, 26, 27, 18],
       [19, 10, 20, 18],
       [14, 29, 26, 14]])

#uniqe()

In [ ]:
np.unique(arr)

array([10, 14, 18, 19, 20, 25, 26, 27, 29])

#sort()

In [ ]:
np.sort(arr,axis=1)  # moving along the column

array([[10, 14, 19, 25],
       [18, 26, 27, 27],
       [10, 18, 19, 20],
       [14, 14, 26, 29]])

In [ ]:
np.sort(arr,axis=0)  # moving along the row

array([[14, 10, 20, 10],
       [19, 14, 25, 14],
       [19, 26, 26, 18],
       [27, 29, 27, 18]])

In [ ]:
np.sort(arr, axis=None)   # sorts the entire array element by element and fives a flattened output

array([10, 10, 14, 14, 14, 18, 18, 19, 19, 20, 25, 26, 26, 27, 27, 29])

# where()

In [ ]:
arr

array([[19, 14, 25, 10],
       [27, 26, 27, 18],
       [19, 10, 20, 18],
       [14, 29, 26, 14]])

In [ ]:
arr>20

array([[False, False,  True, False],
       [ True,  True,  True, False],
       [False, False, False, False],
       [False,  True,  True, False]])

In [ ]:
true_indexes=np.where(arr>20)
true_indexes

(array([0, 1, 1, 1, 3, 3]), array([2, 0, 1, 2, 1, 2]))

In [ ]:
arr[true_indexes]

array([25, 27, 26, 27, 29, 26])

#mean()

In [ ]:
arr

array([[19, 14, 25, 10],
       [27, 26, 27, 18],
       [19, 10, 20, 18],
       [14, 29, 26, 14]])

In [ ]:
arr.mean()

np.float64(19.75)

In [ ]:
arr.mean(axis=1)

array([17.  , 24.5 , 16.75, 20.75])

In [ ]:
arr.mean(axis=0)

array([19.75, 19.75, 24.5 , 15.  ])

# median()

In [ ]:
# median is the mid value in the sorted data
# for even number of count, mid is calculated by taking the average of mid two values

In [ ]:
arr

array([[19, 14, 25, 10],
       [27, 26, 27, 18],
       [19, 10, 20, 18],
       [14, 29, 26, 14]])

In [ ]:
np.median(arr)

np.float64(19.0)

# Standard Deviation

In [ ]:
np.std(arr)

np.float64(6.0878978309429606)

In [ ]:
19.75-2*6 , 19.75+2*6

(7.75, 31.75)

# Reshaping & Combining